fix: Fix errors when run with missing args
- Validate that query arg provided
- Add default for 'parallel' arg
- Fixed error when no args passed (i.e. `python ctdl/ctdl.py`) including `AttributeError: 'NoneType' object has no attribute 'replace'`
- Fixed `IndentationError: unindent does not match any outer indentation level`